
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://donplweigpesvzqczcvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbnBsd2VpZ3Blc3Z6cWN6Y3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0MTkyNzksImV4cCI6MjA1NTk5NTI3OX0.W9jg9X8r1Shm125esVYNTq49yEKY2mt7l2Qv3iLigaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
